name: "React frontend CI"

# events
on:
  push:
    branches: ["main", "develop"]
    # paths
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main", "develop"]
    # paths
    paths:
      - "frontend/**"

env:
  node_version: 22.x
defaults:
  run:
    working-directory: ./frontend
jobs:
  build: #first job
    runs-on: ubutnu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.5 # action
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      - name: Run npm clean install
        run: npm ci
      
      - run: npm run build --if-present
  
